code/Metal Webapp/Metal Webapp/Controllers/BandController.cs
using Microsoft.AspNetCore.Mvc;
using BLL;
using DAL;
using Metal_Webapp.Models;

namespace Metal_Webapp
{
    public class BandController : Controller
    {
        private BandContainer containerBand = new BandContainer(new BandContext());
        private ConcertContainer containerConcert = new ConcertContainer(new ConcertContext());
        private ConvertBand convert = new ConvertBand();
        private ConvertConcert convertConcert = new ConvertConcert();


        public IActionResult Index()
        {
            // Show all bands

            List<BandViewModel> bands = containerBand.GetAll().Select(convert.ConvertToBandViewModel).ToList();

            return View(bands);
        }

        // Access for admin only
        public IActionResult Admin()
        {
            if (HttpContext.Session == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (HttpContext.Session.GetString("username") != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Show all bands

                List<BandViewModel> bands = containerBand.GetAll().Select(convert.ConvertToBandViewModel).ToList();

                return View(bands);
            }
        }
        public IActionResult DeleteBand(int id)
        {
            if (ModelState.IsValid)
            {
                // Delete band by id

                containerBand.DeleteBand(containerBand.GetByID(id));
                TempData["Succes"] = "Band is verwijderd!";
                return RedirectToAction("Admin");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Bandaanmaken()
        {
            if (HttpContext.Session == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (HttpContext.Session.GetString("username") != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {           
                return View();
            }
        }

        [HttpPost]
        public IActionResult Bandaanmaken(BandViewModel b)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Add new band

                    containerBand.AddBand(convert.ConvertBandModel(b));
                    TempData["Succes"] = "Band is aangemaakt!";
                    return RedirectToAction("Admin");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            return View();
        }
        [HttpGet]
        public IActionResult Bandaanpassen(int id)
        {
            // Get band by selected id
            if (HttpContext.Session == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (HttpContext.Session.GetString("username") != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                BandViewModel bands = convert.ConvertToBandViewModel(containerBand.GetByID(id));

                return View(bands);
            }
        }

        [HttpPost]
        public IActionResult Bandaanpassen(BandViewModel b)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Edit selected band

                    containerBand.UpdateBand(convert.ConvertBandModel(b));
                    TempData["Succes"] = "Band is aangepast!";
                    return RedirectToAction("Admin");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return View();
        }
        public IActionResult Gegevens(int id)
        {
            BandLibrary bl = new BandLibrary();

            // Show info from selected band

            BandViewModel bands = convert.ConvertToBandViewModel(containerBand.GetByID(id));

            // Get all concerts from selected band

            List<ConcertViewModel> concerts = containerConcert.GetConcertsByBand(id).Select(convertConcert.ConvertToConcertViewModel).ToList();


            // Add bands and concerts to BandLibrary

            bl.Band = bands;
            bl.ConcertList = concerts;

            return View(bl);

        }
    }
}

code/Metal Webapp/Metal Webapp/Controllers/ConcertController.cs
using Microsoft.AspNetCore.Mvc;
using DAL;
using BLL;
using Metal_Webapp.Models;

namespace Metal_Webapp
{
    public class ConcertController : Controller
    {

        public ConcertContainer container = new ConcertContainer(new ConcertContext());
        private ConcertzaalContainer containerConcertzaal = new ConcertzaalContainer(new ConcertzaalContext());
        private BandContainer containerBand = new BandContainer(new BandContext());
        private ConvertConcert convert = new ConvertConcert();
        private ConvertBand convertBand = new ConvertBand();
        private ConvertConcertzaal convertConcertzaal = new ConvertConcertzaal();

        public IActionResult Index()
        {
            // Show all concerten

            List<ConcertViewModel> concerts = container.GetAll().Select(convert.ConvertToConcertViewModel).ToList();

            return View(concerts);

        }
        public IActionResult Admin()
        {
            // Access for admin only

            if (HttpContext.Session == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (HttpContext.Session.GetString("username") != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Show all concerten

                List<ConcertViewModel> concerts = container.GetAll().Select(convert.ConvertToConcertViewModel).ToList();

                return View(concerts);
            }
        }

        [HttpGet]
        public IActionResult Concertaanmaken()
        {
            if (HttpContext.Session == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (HttpContext.Session.GetString("username") != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Get all concerten, bands and concertzalen

                List<BandViewModel> bands = containerBand.GetAll().Select(convertBand.ConvertToBandViewModel).ToList();
                List<ConcertzaalViewModel> concertzalen = containerConcertzaal.GetAll().Select(convertConcertzaal.ConvertToConcertzaalViewModel).ToList();

                // Add everything to AllClasses

                AllClasses model = new AllClasses();
                model.BandList = bands;
                model.ConcertzaalList = concertzalen;

                return View(model);
            }
        }
        [HttpPost]
        public IActionResult Concertaanmaken(AllClasses c)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    // Add concert

                    ConcertViewModel concert = new ConcertViewModel() { BandID = c.BandModelID, ConcertzaalID = c.ConcertzaalModelID, Datum = c.Datum, BeginTijd = c.BeginTijd, EindTijd = c.EindTijd };
                    container.AddConcert(convert.ConvertConcertModel(concert));
                 
                    TempData["Succes"] = "Concert is aangemaakt!";
                    
                    return RedirectToAction("Admin");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            return View(c);
        }
        public IActionResult DeleteConcert(int id)
        {
            if (ModelState.IsValid)
            {
                // Delete concert

                container.DeleteConcert(container.GetByID(id));

                TempData["Succes"] = "Concert is verwijderd!";
                return RedirectToAction("Admin");
            }
            return View();
        }

        public IActionResult Gegevens(int id)
        {
            ConcertViewModel concerts = convert.ConvertToConcertViewModel(container.GetByID(id));
    
            return View(concerts);

        }
        [HttpGet]
        public IActionResult Concertaanpassen(int id)
        {
            if (HttpContext.Session == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (HttpContext.Session.GetString("username") != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Get concert by id

                ConcertViewModel concerts = convert.ConvertToConcertViewModel(container.GetByID(id));

                return View(concerts);
            }
        }

        [HttpPost]
        public IActionResult Concertaanpassen(ConcertViewModel c)
        {
            ModelState.Remove("banddto");
            ModelState.Remove("BandNaam");
            ModelState.Remove("BandInfo");
            ModelState.Remove("ConcertzaalNaam");
            ModelState.Remove("Locatie");
            ModelState.Remove("Land");
            try
            {
                if (ModelState.IsValid)
                {
                    // Update selected concert

                    container.UpdateConcert(convert.ConvertConcertModel(c));
                    TempData["Succes"] = "Concert is aangepast!";
                    return RedirectToAction("Admin");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return View();
        }
    }  
}

code/Metal Webapp/Metal Webapp/Controllers/ConcertzaalController.cs
using Microsoft.AspNetCore.Mvc;
using DAL;
using Metal_Webapp.Models;
using BLL;

namespace Metal_Webapp.Controllers
{
    public class ConcertzaalController : Controller
    {
        private ConcertzaalContainer containerConcertzaal = new ConcertzaalContainer(new ConcertzaalContext());
        private ConcertContainer containerConcert = new ConcertContainer(new ConcertContext());
        private ConvertConcertzaal convert = new ConvertConcertzaal();
        private ConvertConcert convertConcert = new ConvertConcert();


        public IActionResult Index()
        {
            // Get all concertzalen

            List<ConcertzaalViewModel> concertzalen = containerConcertzaal.GetAll().Select(convert.ConvertToConcertzaalViewModel).ToList();
            return View(concertzalen);

        }

        public IActionResult Gegevens(int id)
        {
            BandLibrary bl = new BandLibrary();

            // Get info concertzaal by id

            ConcertzaalViewModel concertzalen = convert.ConvertToConcertzaalViewModel(containerConcertzaal.GetByID(id));

            // Get all concerten by selected concertzaal

            List<ConcertViewModel> concerts = containerConcert.GetConcertsByConcertzaal(id).Select(convertConcert.ConvertToConcertViewModel).ToList();


            bl.ConcertzaalInfo = concertzalen;
            bl.ConcertList = concerts;

            return View(bl);

        }
        public IActionResult Admin()
        {
            // Admin access only

            if (HttpContext.Session == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (HttpContext.Session.GetString("username") != "admin")
            {
                return RedirectToAction("Admin", "Home");
            }
            else
            {
                // Get all concertzalen

                List<ConcertzaalViewModel> concertzalen = containerConcertzaal.GetAll().Select(convert.ConvertToConcertzaalViewModel).ToList();
                return View(concertzalen);
            }
        }

        public IActionResult DeleteConcertzaal(int id)
        {
            if (ModelState.IsValid)
            {
                // Delete concertzaal selected by id

                containerConcertzaal.DeleteConcertzaal(containerConcertzaal.GetByID(id));
                TempData["Succes"] = "Concertzaal is verwijderd!";
                return RedirectToAction("Admin");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Concertzaalaanpassen(int id)
        {
            if (HttpContext.Session == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (HttpContext.Session.GetString("username") != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Select concertzaal by id

                ConcertzaalViewModel concertzalen = convert.ConvertToConcertzaalViewModel(containerConcertzaal.GetByID(id));

                return View(concertzalen);
            }
        }

        [HttpPost]
        public IActionResult Concertzaalaanpassen(ConcertzaalViewModel concertzaal)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Update selected concertzaal

                    containerConcertzaal.UpdateConcertzaal(convert.ConvertConcertzaalModel(concertzaal));
                    TempData["Succes"] = "Concertzaal is aangepast!";
                    return RedirectToAction("Admin");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return View();
        }
        [HttpGet]
        public IActionResult Concertzaalaanmaken()
        {
            if (HttpContext.Session == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (HttpContext.Session.GetString("username") != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult Concertzaalaanmaken(ConcertzaalViewModel cz)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Add new concertzaal

                    containerConcertzaal.AddConcertzaal(convert.ConvertConcertzaalModel(cz));
                    TempData["Succes"] = "Concertzaal is aangemaakt!";
                    return RedirectToAction("Admin");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            return View();
        }

    }
}

code/Metal Webapp/Metal Webapp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Metal_Webapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Metal_Webapp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://th.bing.com/th/id/R.dec7477029e165aad139408d39c9146e?rik=XccL8wJntKjX4A&pid=ImgRaw&r=0" style="width: 50px"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Concert" asp-action="Index">Concerten</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Band" asp-action="Index">Bands</a>
                        </li>                      
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Concertzaal" asp-action="Index">Concertzalen</a>
                        </li>                                                  
                          
                    </ul>
                    <ul class="navbar-nav">
                        @if (Context.Session.GetString("username") != null)
                            {
                                string username = Context.Session.GetString("username");
                                int? id = Context.Session.GetInt32("id");

                                
                                if (Context.Session.GetString("username") == "admin")
                                {
                                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">Admin menu</a></li> 
                                }
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Gebruiker" asp-action="Profiel" asp-route-id=@id>@username</a></li>    
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Gebruiker" asp-action="Uitloggen">Uitloggen</a></li>
                            }
                            else
                            { 
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Gebruiker" asp-action="Index">Inloggen</a></li>
                            }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2022 - Metal_Webapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>